version: '3.4'

services:
  nodets:
    image: nodets
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9988:9988
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
